abstract class AppConstVariables {
  static const widthInfinity = double.infinity;
  static const h2hRatioBar = 148;
  static const statsBarWidth = 180.00;
  static const ballPossessionSum = 100;
  static const dateYyyyMmDdDashFormat = 'yyyy-MM-dd';
  static const dateMmmDYyyyWithComaFormat = 'MMM d, yyyy';
  static const stringPlaceholder = '';
  static const intPlaceholder = 0;
  static const fullTime = 'FT';
  static const matchTimeToBeDefined = 'TBD';
  static const matchNotStarted = 'NS';
  static const matchSuspended = 'SUSP';
  static const goal = 'Goal';
  static const normalGoal = 'Normal Goal';
  static const ownGoal = 'Own Goal';
  static const penaltyGoal = 'Penalty';
  static const penaltyMissed = 'Missed Penalty';
  static const card = 'Card';
  static const yellowCard = 'Yellow Card';
  static const redCard = 'Red Card';
  static const substitution = 'subst';
  static const varCheck = 'var';
  static const varGoalCancelled = 'Goal cancelled';
  static const varPenaltyConfirmed = 'Penalty Confirmed';
  static const standingsHeadersText = ['PL', 'W', 'D', 'L', 'GD', 'PTS'];
  static const goalsHeader = 'Goals';
  static const assistsHeader = 'Assists';
}
